<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Outbox_101.Domain\Outbox_101.Domain.csproj" />
    <ProjectReference Include="..\Outbox_101.Infrastructure.Kafka\Outbox_101.Infrastructure.Kafka.csproj" />
  </ItemGroup>

</Project>
